export default {
    install(Vue) {
        //签诗-签文百首数组
        Vue.prototype.DrawPoetryArray = (i) => {
            i = i || 100;
            var array = [
                { index: '第一百签', content: '唐明皇祷告天', zg: '癸癸', brief: '上上' },
                { index: '第九十九签', content: '百里奚投秦', zg: '癸癸', brief: '上上' },
                { index: '第九十八签', content: '薛仁贵投军', zg: '癸辛', brief: '中平' },
                { index: '第九十七签', content: '买臣五十富贵', zg: '癸庚', brief: '上上' },
                { index: '第九十五签', content: '张文远求官', zg: '癸戊', brief: '中平' },
                { index: '第九十六签', content: '山涛见王衍', zg: '癸己', brief: '上吉' },
                { index: '第九十四签', content: '提结过长者门', zg: '癸丁', brief: '中平' },
                { index: '第九十三签', content: '邵康节定阴阳', zg: '癸丙', brief: '中平' },
                { index: '第九十二签', content: '高祖治汉民', zg: '癸乙', brief: '下下' },
                { index: '第九十一签', content: '赵子龙抱太子', zg: '癸甲', brief: '中平' },
                { index: '第九十签', content: '杨文广陷柳州', zg: '壬癸', brief: '中平' },
                { index: '第八十九签', content: '班超归玉门关', zg: '壬壬', brief: '中平' },
                { index: '第八十八签', content: '高文定守困', zg: '壬辛', brief: '上吉' },
                { index: '第八十七签', content: '武侯与子敬同舟', zg: '壬庚', brief: '下下' },
                { index: '第八十六签', content: '管鲍为贾', zg: '壬己', brief: '上上' },
                { index: '第八十五签', content: '姜女寻夫', zg: '壬戊', brief: '中平' },
                { index: '第八十四签', content: '须贾害范睢', zg: '壬丁', brief: '中平' },
                { index: '第八十三签', content: '诸葛孔明学道', zg: '壬丙', brief: '下下' },
                { index: '第八十二签', content: '宋仁宗认母', zg: '壬乙', brief: '上吉' },
                { index: '第八十一签', content: '寇公任雷阳', zg: '壬甲', brief: '中平' },
                { index: '第八十签', content: '郭璞为母卜葬', zg: '辛癸', brief: '下下' },
                { index: '第七十九签', content: '文王编易卦', zg: '辛壬', brief: '中平' },
                { index: '第七十八签', content: '袁安守困', zg: '辛辛', brief: '下下' },
                { index: '第七十七签', content: '吕后害韩信', zg: '辛庚', brief: '下下' },
                { index: '第七十六签', content: '萧何注律', zg: '辛己', brief: '中平' },
                { index: '第七十五签', content: '刘小姐爱蒙正', zg: '辛戊', brief: '上吉' },
                { index: '第七十四签', content: '崔武求官', zg: '辛丁', brief: '上吉' },
                { index: '第七十三签', content: '王昭君忆汉帝', zg: '辛丙', brief: '下下' },
                { index: '第七十二签', content: '范蠡归湖', zg: '辛乙', brief: '下下' },
                { index: '第七十一签', content: '苏武还乡', zg: '辛甲', brief: '中平' },
                { index: '第七十签', content: '王曾祈祷', zg: '庚癸', brief: '中平' },
                { index: '第六十九签', content: '孙庞斗智', zg: '庚壬', brief: '下下' },
                { index: '第六十八签', content: '钱大王贩盐', zg: '庚辛', brief: '中平' },
                { index: '第六十七签', content: '江遗嘱儿', zg: '庚庚', brief: '中平' },
                { index: '第六十六签', content: '杜甫游春', zg: '庚己', brief: '上上' },
                { index: '第六十五签', content: '蒙正木兰和诗', zg: '庚戊', brief: '上上' },
                { index: '第六十四签', content: '管鲍分金', 庚zg: '丁', 上brief: ' 上' },
                { index: '第六十三签', content: '杨令公撞李陵碑', zg: '庚丙', brief: '中平' },
                { index: '第六十二签', content: '韩信占霸王', zg: '庚乙', brief: '中平' },
                { index: '第六十一签', content: '蒯辄见韩信', zg: '庚甲', brief: '中平' },
                { index: '第六十签', content: '宋郊兄弟同科', zg: '己癸', brief: '上上' },
                { index: '第五十九签', content: '邓伯道无儿', zg: '己壬', brief: '中平' },
                { index: '第五十八签', content: '苏秦背剑', zg: '己辛', brief: '上吉' },
                { index: '第五十七签', content: '烂柯观棋', zg: '己庚', brief: '中平' },
                { index: '第五十六签', content: '五枢密奸险', zg: '己巳', brief: '下下' },
                { index: '第五十五签', content: '包龙图劝农', zg: '己戊', brief: '中平' },
                { index: '第五十四签', content: '苏秦刺股', zg: '己丁', brief: '中平' },
                { index: '第五十三签', content: '刘先主入赘孙权妹', zg: '己丙', brief: '下下' },
                { index: '第五十二签', content: '匡衡夜读书', zg: '己乙', brief: '上吉' },
                { index: '第五十一签', content: '御沟流红叶', zg: '己甲', brief: '上吉' },
                { index: '第五十签', content: '苏东坡功民', zg: '戊癸', brief: '上吉' },
                { index: '第四十九签', content: '张子房遁迹', zg: '戊壬', brief: '下下' },
                { index: '第四十八签', content: '赵五娘寻夫', zg: '戊辛', brief: '中平' },
                { index: '第四十七签', content: '楚汉争锋', zg: '戊庚', brief: '下下' },
                { index: '第四十六签', content: '孤儿报冤', zg: '戊己', brief: '中平' },
                { index: '第四十五签', content: '高祖遇丁公', zg: '戊戊', brief: '中平' },
                { index: '第四十四签', content: '王莽篡位', zg: '戊丁', brief: '中平' },
                { index: '第四十三签', content: '玄德公黄鹤楼赴宴', zg: '戊丙', brief: '中吉' },
                { index: '第四十二签', content: '董永卖身', zg: '戊乙', brief: '中吉' },
                { index: '第四十一签', content: '刘文龙求官', zg: '戊申', brief: '中吉' },
                { index: '第四十签', content: '汉光武陷昆明', zg: '丁癸', brief: '上吉' },
                { index: '第三十九签', content: '陶渊明赏菊', zg: '丁壬', brief: '下下' },
                { index: '第三十八签', content: '孟姜女思夫', zg: '丁辛', brief: '下下' },
                { index: '第三十七签', content: '邵尧夫祝香', zg: '丁庚', brief: '中平' },
                { index: '第三十六签', content: '罗隐求官', zg: '丁己', brief: '上吉' },
                { index: '第三十五签', content: '王昭君和番', zg: '丁戊', brief: '下下' },
                { index: '第三十四签', content: '萧何追韩信', zg: '丁丁', brief: '中平' },
                { index: '第三十三签', content: '庄子慕道', zg: '丁丙', brief: '中平' },
                { index: '第三十二签', content: '周公解梦', zg: '丁乙', brief: '下下' },
                { index: '第三十一签', content: '苏卿负信', zg: '丁甲', brief: '中吉' },
                { index: '第三十签', content: '柳毅传书', zg: '丙癸', brief: '中吉' },
                { index: '第二十九签', content: '司马温公嗟困', zg: '丙壬', brief: '上上' },
                { index: '第二十八签', content: '相如题桥', zg: '丙辛', brief: '上吉' },
                { index: '第二十七签', content: '江东得道', zg: '丙庚', brief: '下下' },
                { index: '第二十六签', content: '邵尧夫告天', zg: '丙己', brief: '中吉' },
                { index: '第二十五签', content: '唐明皇游月宫', zg: '丙戊', brief: '中平' },
                { index: '第二十四签', content: '张骞误入斗牛宫', zg: '丙丁', brief: '中平' },
                { index: '第二十三签', content: '吴王爱西施', zg: '丙丙', brief: '下下' },
                { index: '第二十二签', content: '李太白遇唐明皇', zg: '丙乙', brief: '上吉' },
                { index: '第二十一签', content: '孙庞斗智结仇', zg: '丙甲', brief: '下下' },
                { index: '第二十签', content: '严子陵登钓台', zg: '乙癸', brief: '下下' },
                { index: '第十九签', content: '刘智远得岳氏', zg: '乙壬', brief: '上吉' },
                { index: '第十八签', content: '孟尝君招贤', zg: '乙辛', brief: '中平' },
                { index: '第十七签', content: '石崇被难', zg: '乙庚', brief: '下下' },
                { index: '第十六签', content: '王祥卧冰', zg: '乙己', brief: '下下' },
                { index: '第十五签', content: '张君瑞忆莺莺', zg: '乙戊', brief: '中平' },
                { index: '第十四签', content: '郭华恋王月英', zg: '乙丁', brief: '下下' },
                { index: '第十三签', content: '姜太公钓鱼', zg: '乙丙', brief: '中下' },
                { index: '第十二签', content: '苏武牧羊', zg: '乙乙', brief: '下下' },
                { index: '第十一签', content: '韩信功劳不久', zg: '乙甲', brief: '下下' },
                { index: '第十签', content: '冉伯牛染疾', zg: '甲癸', brief: '下下' },
                { index: '第九签', content: '宋太祖陈桥即位', zg: '甲壬', brief: '大吉' },
                { index: '第八签', content: '大舜耕历山', zg: '甲辛', brief: '上上' },
                { index: '第七签', content: '洞宾练丹', zg: '甲庚', brief: '大吉' },
                { index: '第六签', content: '相如完璧归赵', zg: '甲己', brief: '下下' },
                { index: '第五签', content: '吕蒙正守困', zg: '甲戊', brief: '中平' },
                { index: '第四签', content: '小秦王三跳涧', zg: '甲丁', brief: '下下' },
                { index: '第三签', content: '贾谊遇汉文帝', zg: '甲丙', brief: '中吉' },
                { index: '第二签', content: '张子房游赤松', zg: '甲乙', brief: '上吉' },
                { index: '第一签', content: '汉高祖入关', zg: '甲甲', brief: '大吉' }
            ]
            return array[i];
        }
    }
}